### ISSUE TITLE
Hardcoded Branch Name

### ISSUE THREAD

**Issue by Fishwaldo** [posener/goreadme#118]
Seems for some of the badges, the Branch name is hardcoded into the template. Would be good to make that dynamic as Github has changed the defaults from master to main on new repositories

I see a attempt to fix this was made in #102 (along with other fixes). Could that be cherry picked out?

**Comment by marksalpeter** [comment]
Unfortunately not easily. After I implemented this fix, @posener significantly changed the library 😕. 

If this is really important to you, you can just use [my fork](https://github.com/marksalpeter/goreadme) by referencing the latest commit sha. It will reference whatever your default branch is. It can also add a github action badge to your readme. You can see both in action [here](https://github.com/deliveryhero/pipeline).
```yaml
docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Update readme according to Go doc
      uses: posener/goreadme@e713475bae0c17d5083f4378c5e53d6c66d74c74
      with:
        email: 'email@for.commit'
        badge-codecov: true
        badge-godoc: true
        badge-github: "ci.yml"  # optional for a github action badge. all the others are standard
        badge-goreportcard: true
        badge-travisci: false
        commit-message: 'improvement(docs): updated docs'
        types: true
        functions: true
        github-token: '${{ secrets.GITHUB_TOKEN }}'
 ```
